In [1]:
import numpy as np

In [2]:
ratings = np.array([[3, 3, 4, 0, 4, 2, 3, 0],
                    [3, 5, 4, 3, 3, 0, 0, 4],
                    [0, 4, 0, 5, 0, 0, 2, 1],
                    [2, 0, 0, 4, 0, 4, 4, 5]])
Ub = (ratings>0).astype(int)
print(Ub)

def jaccard(a,b):
    return (a*b).sum()/((a+b)>0).sum()

# Cosine similarity function
def cos(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

users = ["firechicken","mike0702","zephyros","dadvador"]

# Jaccard similarity matrix
print("\nJaccard Similarities:")
jaccard_simmat = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        jaccard_simmat[i, j] = jaccard(Ub[i], Ub[j])
        if i < j:
            print(f"{users[i]}-{users[j]}: {jaccard(Ub[i], Ub[j]):.2f}")

print("\nJaccard Similarity Matrix:")
print(jaccard_simmat)

# Cosine similarity matrix
print("\nCosine Similarities:")
cos_simmat = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        cos_simmat[i, j] = cos(Ub[i], Ub[j])
        if i < j:
            print(f"{users[i]}-{users[j]}: {cos(Ub[i], Ub[j]):.2f}")

print("\nCosine Similarity Matrix:")
print(cos_simmat)

[[1 1 1 0 1 1 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 1 1]
 [1 0 0 1 0 1 1 1]]

Jaccard Similarities:
firechicken-mike0702: 0.50
firechicken-zephyros: 0.25
firechicken-dadvador: 0.38
mike0702-zephyros: 0.43
mike0702-dadvador: 0.38
zephyros-dadvador: 0.50

Jaccard Similarity Matrix:
[[1.         0.5        0.25       0.375     ]
 [0.5        1.         0.42857143 0.375     ]
 [0.25       0.42857143 1.         0.5       ]
 [0.375      0.375      0.5        1.        ]]

Cosine Similarities:
firechicken-mike0702: 0.67
firechicken-zephyros: 0.41
firechicken-dadvador: 0.55
mike0702-zephyros: 0.61
mike0702-dadvador: 0.55
zephyros-dadvador: 0.67

Cosine Similarity Matrix:
[[1.         0.66666667 0.40824829 0.54772256]
 [0.66666667 1.         0.61237244 0.54772256]
 [0.40824829 0.61237244 1.         0.67082039]
 [0.54772256 0.54772256 0.67082039 1.        ]]


In [3]:
import numpy as np

# Ratings matrix
ratings = np.array([[3, 3, 4, 0, 4, 2, 3, 0],
                    [3, 5, 4, 3, 3, 0, 0, 4],
                    [0, 4, 0, 5, 0, 0, 2, 1],
                    [2, 0, 0, 4, 0, 4, 4, 5]])

# Convert ratings to binary good (1) vs. bad (0)
Ur = (ratings >= 3).astype(int)
print("Binary Good vs. Bad Ratings:")
print(Ur)

# Jaccard similarity function
def jaccard(a, b):
    return (a * b).sum() / ((a + b) > 0).sum()

users = ["firechicken", "mike0702", "zephyros", "dadvador"]

# Jaccard similarity matrix for good vs. bad ratings
print("\nJaccard Similarities (Good vs. Bad):")
jaccard_simmat = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        jaccard_simmat[i, j] = jaccard(Ur[i], Ur[j])
        if i < j:
            print(f"{users[i]}-{users[j]}: {jaccard(Ur[i], Ur[j]):.3f}")

print("\nJaccard Similarity Matrix (Good vs. Bad):")
print(jaccard_simmat)


Binary Good vs. Bad Ratings:
[[1 1 1 0 1 0 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 1 1]]

Jaccard Similarities (Good vs. Bad):
firechicken-mike0702: 0.571
firechicken-zephyros: 0.167
firechicken-dadvador: 0.125
mike0702-zephyros: 0.333
mike0702-dadvador: 0.250
zephyros-dadvador: 0.200

Jaccard Similarity Matrix (Good vs. Bad):
[[1.         0.57142857 0.16666667 0.125     ]
 [0.57142857 1.         0.33333333 0.25      ]
 [0.16666667 0.33333333 1.         0.2       ]
 [0.125      0.25       0.2        1.        ]]


In [4]:
# Treating the utility matrix as boolean (buy or not buy), 
# compute the Jaccard distance between zephyros and dadvador. Please answer to two decimal places.

ratings = np.array([[3, 3, 4, 0, 4, 2, 3, 0],
                    [3, 5, 4, 3, 3, 0, 0, 4],
                    [0, 4, 0, 5, 0, 0, 2, 1],
                    [2, 0, 0, 4, 0, 4, 4, 5]])
Ub = (ratings>0).astype(int)
print(Ub)

def jaccard(a,b):
    return (a*b).sum()/((a+b)>0).sum()

users = ["firechicken","mike0702","zephyros","dadvador"]

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = jaccard(Ub[i],Ub[j])
        if i<j:
            print(users[i]+'-'+users[j], jaccard(Ub[i],Ub[j]))

print(simmat)

[[1 1 1 0 1 1 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 1 1]
 [1 0 0 1 0 1 1 1]]
firechicken-mike0702 0.5
firechicken-zephyros 0.25
firechicken-dadvador 0.375
mike0702-zephyros 0.42857142857142855
mike0702-dadvador 0.375
zephyros-dadvador 0.5
[[1.         0.5        0.25       0.375     ]
 [0.5        1.         0.42857143 0.375     ]
 [0.25       0.42857143 1.         0.5       ]
 [0.375      0.375      0.5        1.        ]]


In [5]:
# Treating the utility matrix as boolean (buy or not buy), 
# compute the Cosine  distance between zephyros and dadvador. Please answer to three decimal places.

def cos(a,b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = cos(Ub[i],Ub[j])
        if i<j:
            print(users[i]+'-'+users[j], cos(Ub[i],Ub[j]))
print(simmat)     

firechicken-mike0702 0.6666666666666667
firechicken-zephyros 0.4082482904638631
firechicken-dadvador 0.5477225575051661
mike0702-zephyros 0.6123724356957946
mike0702-dadvador 0.5477225575051661
zephyros-dadvador 0.6708203932499369
[[1.         0.66666667 0.40824829 0.54772256]
 [0.66666667 1.         0.61237244 0.54772256]
 [0.40824829 0.61237244 1.         0.67082039]
 [0.54772256 0.54772256 0.67082039 1.        ]]


In [6]:
# Now, let's convert user ratings to good vs. bad. We consider it's good (1) if the rating is 3 or above, and bad (0) otherwise. Compute the Jaccard distance between mike0702 and zephyros. Please answer to three decimal places.

Ur = (ratings>=3).astype(int)
print(Ur)

simmat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        simmat[i,j] = jaccard(Ur[i],Ur[j])
        if i<j:
            print(users[i]+'-'+users[j], jaccard(Ur[i],Ur[j]))

[[1 1 1 0 1 0 1 0]
 [1 1 1 1 1 0 0 1]
 [0 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 1 1]]
firechicken-mike0702 0.5714285714285714
firechicken-zephyros 0.16666666666666666
firechicken-dadvador 0.125
mike0702-zephyros 0.3333333333333333
mike0702-dadvador 0.25
zephyros-dadvador 0.2
